### ISSUE TITLE
The renderCountryOptions isn't returning the countries

### ISSUE THREAD

**Issue by nitink66** [jgbijlsma/corona-dashboard#1]
The  `renderCountryOptions(){
  return this.state.countries.map((country,i)=>{
      return <option key={i}>{country}</option>
  });
}`
isn't returning the countries instead it is returning the numbers inside the select options.
![1](https://user-images.githubusercontent.com/60770391/77390805-0e09ef00-6dbd-11ea-8b12-03ccaba12d5e.jpg)

**Comment by forloulhoucine** [comment]
The renderCountryOptions isn't returning the countries because the api changed his structure ..any solution please tell me

**Comment by nayangogoi744** [comment]
Facing the same. Anyone there. please help

**Comment by nitink66** [comment]
I have changed the code ,
Refer my repo it will help you :)
https://github.com/nitink66/corona-updates/blob/master/src/App.js

**Comment by jgbijlsma** [comment]
> I have changed the code ,
> Refer my repo it will help you :)
> https://github.com/nitink66/corona-updates/blob/master/src/App.js

Nice, I'll update my code too.

**Comment by mozi47** [comment]
Here is the Code for displaying the countries name
const world=await Axio.get("https://covid19.mathdro.id/api/countries")
    const Countries=[]
    const getcountry=world.data.countries
    for (let i in getcountry){
      Countries.push(getcountry[i].name)
      //console.log(Countries[i])
      //console.log(getcountry[i].name)
    }

**Comment by rohan-buchner** [comment]
Has this fix been deployed yet to the live app? (Doesn't seem like it)

**Comment by nitink66** [comment]
@rohan-buchner nope !
I have developed the repo using the same code he has used, and have changed the code for rendercountryoptions() .
Might Help you 
Repo:
[https://github.com/nitink66/corona-updates](url)
